name: Build JAR

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure GCloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Build JAR
        run: sbt package
      - name: Determine JAR and scala version
        run: |
          python3 version.py > version.txt &&
          echo "JAR_VERSION=$(head -n 1 version.txt)" >> $GITHUB_ENV &&
          echo "SCALA_VERSION=$(tail -n 1 version.txt)" >> $GITHUB_ENV &&
            rm version.txt

      - name: Define Jar Path
        run: |
          echo "JAR_PATH=target/scala-${{ env.SCALA_VERSION }}/loppronostic_${{ env.SCALA_VERSION }}-${{ env.JAR_VERSION }}.jar" >> $GITHUB_ENV


      - name: Deploy to Cloud Storage
        run: |
          echo "JAR_PATH=${{ env.JAR_PATH }}" &&
          gsutil cp ${{ env.JAR_PATH }} gs://lopprono/$JAR_NAME.jar &&
          gsutil cp ${{ env.JAR_PATH }}" gs://lopprono/main.jar 
